handle subscriber to custodian payment
Dygnify/GreenBondServer pull request #7
Opened 2024-05-08 12:52 UTC by swadhinbubaipaul

2024-05-11 16:35 UTC, DnyaneshWarade requested changes

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/emailHelper.js
> +      <p>The subscription amount of ${amount} towards instrument ${bondName} has been received and acknowledged by Custodian.</p>
Use function to format amount like it has been used in other email format

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/emailHelper.js
> +      <p>The subscription amount of ${amount} towards instrument ${bondName} has been not been received by Custodian.</p>
Same comment for this

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/emailHelper.js
> +      <p>The disbursement amount of ${amount} towards instrument ${bondName} has been received and acknowledged by Issuer.</p>
same

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/emailHelper.js
> +      <p>The disbursement amount of ${amount} towards instrument ${bondName} has been not been received by Issuer.</p>
same

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/amortisation/amortisationSchedule.js
Why this file is coming as completely new file?
I can see this is been moved to new folder but then it's deleted file should also come as change in old location

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/getTx.js
Why this is separate file and not part of old transaction.js?

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/transaction.js
> +					bond = await getGreenBond({
Move this code to separate function as it is very long and unreadable
make smaller logical functions

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/transaction.js
> +
We must check the success of createGreenBond call before sending email

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/transaction.js
> +					bond = await getGreenBond({
We must have try catch under each case block to handle crash scenarios

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/transaction.js
> +					let stringObj = JSON.stringify(scoreResult.res);
Hash creation can be a separate function in common area and should be used here

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/transaction.js
> +					await DisbursementFundsSuccess(
check for success of above steps then only call for email sending

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/transaction.js
> +const getGreenScore = async (email, projectId) => {
Following functions are not part of transaction so can be placed in different file with appropriate file name under services

2024-05-11 16:35 UTC, DnyaneshWarade commented on functions/services/hyperLedgerFunctions/transaction.js
> +const getUserProfile = async (email) => {
this function can be part of users file instead of transaction and also id function above does the same work so it can be also be  combined with this function to take either id or email and return the result

2024-05-13 13:30 UTC, swadhinbubaipaul commented on functions/services/hyperLedgerFunctions/getTx.js
Sir as I mentioned earlier that GreenBond is importing getTx from transactions and transactions importing createGreenBond and getGreenBond from GreenBond. This creates circular dependency issue. That's why, I have created a separate getTx file and importing in GreenBond.

2024-05-13 15:20 UTC, DnyaneshWarade approved these changes

2024-05-13 15:21 UTC, merged